name: net

services:
  headscale:
    image: headscale
    build:
      context: ../headscale
      network: host
      args:
        BASE_ALPINE: "alpine:3.17"
        BASE_GOLANG: "golang:1.20-alpine3.17"
        GOPROXY: "https://goproxy.cn,direct"
        ALL_PROXY:
    restart: unless-stopped
    volumes:
      - hs_01:/var/lib/headscale

  tailscale:
    image: tailscale
    build:
      context: ../tailscale
      network: host
      args:
        BASE_ALPINE: "alpine:3.17"
        BASE_GOLANG: "golang:1.20-alpine3.17"
        GOPROXY: "https://goproxy.cn,direct"
        ALL_PROXY:
    network_mode: host
    restart: unless-stopped
    environment:
      TS_AUTHKEY:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SOCKET: /run/tailscale/tailscaled.sock
      TS_EXTRA_ARGS: "--netfilter-mode off"
      TS_TAILSCALED_EXTRA_ARGS: "-tun ts_0"
      TS_USERSPACE: false
    volumes:
      - ts_01:/var/lib/tailscale
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW

volumes:
  hs_01:
  ts_01:
